import { ChangeDetectionStrategy, ChangeDetectorRef, Component, Input, SkipSelf } from '@angular/core';
import { JsfLayoutEditor }                                                        from '@kalmia/jsf-common-es2015';
import { AbstractLayoutBuilderComponent }                                         from '../../../abstract/abstract-layout-builder.component';


@Component({
  selector       : 'jsf-lb-app-page-title',
  template       : `
      <span class="jsf-lb-app-page-title jsf-layout-app-page-title" [ngClass]="getLayoutEditorClass()">{{ title }}</span>
  `,
  changeDetection: ChangeDetectionStrategy.OnPush,
  styleUrls      : ['./lb-app-page-title.component.scss']
})
export class LbAppPageTitleComponent extends AbstractLayoutBuilderComponent {

  @Input()
  layoutEditor: JsfLayoutEditor;

  get title(): string {
    return this.layoutEditor.mutableDefinition.title || '<Autogenerated Page Title>';
  }

  constructor(
    protected cdRef: ChangeDetectorRef,
    @SkipSelf() protected parentCdRef: ChangeDetectorRef
  ) {
    super(cdRef, parentCdRef);
  }

}
